### ISSUE TITLE
test_migemo_query fail on python3

### ISSUE THREAD

**Issue by Hubbitus** [mooz/python-cmigemo#2]
```
+ /usr/bin/python3 setup.py test
test_migemo_get_encoding (test_cmigemo.TestCMigemo) ... ok
test_migemo_get_operator (test_cmigemo.TestCMigemo) ... ok
test_migemo_load (test_cmigemo.TestCMigemo) ... ok
test_migemo_load_not_found (test_cmigemo.TestCMigemo) ... ok
test_migemo_open (test_cmigemo.TestCMigemo) ... ok
test_migemo_query (test_cmigemo.TestCMigemo) ... FAIL
test_migemo_set_operator (test_cmigemo.TestCMigemo) ... ok

======================================================================
FAIL: test_migemo_query (test_cmigemo.TestCMigemo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_cmigemo.py", line 46, in test_migemo_query
    migemo_utf8.query(query_string_unicode.encode("utf-8")))
AssertionError: '(\u30db\u30b2|\u88dc\u5143|\u4fdd\u5143|\u5e06\u6841|\u6355\u9be8|\u307b\u3052)' != '(\u307b\u3052|\u6355\u9be8|\u5e06\u6841|\u4fdd\u5143|\u88dc\u5143|\u30db\u30b2|\uff8e\uff79\uff9e)'
- (\u30db\u30b2|\u88dc\u5143|\u4fdd\u5143|\u5e06\u6841|\u6355\u9be8|\u307b\u3052)
+ (\u307b\u3052|\u6355\u9be8|\u5e06\u6841|\u4fdd\u5143|\u88dc\u5143|\u30db\u30b2|\uff8e\uff79\uff9e)
```

Version 0.1.5

**Comment by zundoya** [comment]
Hi!

I tested the test with python3 and python2.7 on my machine; ubuntu 14.04
Japanese edition.
The test was passed on both python3 and python2.7.
From point of error message, query returns different results. I think that
error might be coused by using different Japanese dictionary. So no problem
to use this module.

I hope this would be helpful for you.
 thanks!

2015-07-27 6:20 GMT+09:00 Pavel Alexeev aka Pahan-Hubbitus <
notifications@github.com>:

**Comment by Hubbitus** [comment]
Hi.
Thanks for the reply.
About what dictionary are you speaking?
I run it in non-Japanese environment and want package for Fedora. Could you please help me fix such problem?

**Comment by mooz** [comment]
Hi @Hubbitus and @zundoya . Thanks for the report. As @zundoya mentioned, this error is caused by the difference between the dictionary you used and the dictionary I used.

Though this error is trivial, I made the test case robust to the difference between dictionaries.

**Comment by Hubbitus** [comment]
Thank you
